"""
Prescription form generation from medical consultation data.
"""

import asyncio
import logging
import json
from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import black, blue
from jinja2 import Template

from ...config.settings import Config
from ..validators.form_validator import FormValidator


class PrescriptionGenerator:
    """Generates prescription forms from medical consultation data."""
    
    def __init__(self, config: Config):
        self.config = config
        self.logger = logging.getLogger(__name__)
        self.validator = FormValidator(config)
        
        # Initialize templates
        self._load_templates()
    
    def _load_templates(self):
        """Load prescription form templates."""
        # Default prescription template
        self.prescription_template = Template("""
        <html>
        <head>
            <title>Prescription - {{ patient_name }}</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; }
                .doctor-info { float: left; width: 48%; }
                .patient-info { float: right; width: 48%; }
                .clear { clear: both; }
                .prescription-body { margin-top: 20px; }
                .medication { margin: 15px 0; padding: 10px; border-left: 3px solid #007bff; }
                .signature { margin-top: 40px; text-align: right; }
                .footer { margin-top: 30px; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>PRESCRIPTION</h1>
                <h3>{{ clinic_name }}</h3>
                <p>{{ clinic_address }} | Phone: {{ clinic_phone }}</p>
            </div>
            
            <div class="doctor-info">
                <h4>Doctor Information:</h4>
                <p><strong>Dr. {{ doctor_name }}</strong></p>
                <p>License: {{ doctor_license }}</p>
                <p>Specialization: {{ doctor_specialty }}</p>
            </div>
            
            <div class="patient-info">
                <h4>Patient Information:</h4>
                <p><strong>{{ patient_name }}</strong></p>
                <p>Patient ID: {{ patient_id }}</p>
                <p>Age: {{ patient_age }}</p>
                <p>Date: {{ prescription_date }}</p>
            </div>
            
            <div class="clear"></div>
            
            <div class="prescription-body">
                <h3>Chief Complaints:</h3>
                <p>{{ symptoms }}</p>
                
                <h3>Diagnosis:</h3>
                <p>{{ diagnosis }}</p>
                
                <h3>Medications Prescribed:</h3>
                {% for medication in medications %}
                <div class="medication">
                    <p><strong>{{ loop.index }}. {{ medication.name }}</strong></p>
                    <p>Dosage: {{ medication.dosage }}</p>
                    <p>Frequency: {{ medication.frequency }}</p>
                    <p>Duration: {{ medication.duration }}</p>
                    <p>Instructions: {{ medication.instructions }}</p>
                </div>
                {% endfor %}
                
                <h3>Additional Instructions:</h3>
                <p>{{ additional_instructions }}</p>
                
                <h3>Follow-up:</h3>
                <p>{{ follow_up_instructions }}</p>
            </div>
            
            <div class="signature">
                <p>____________________________</p>
                <p>Dr. {{ doctor_name }}</p>
                <p>Digital Signature</p>
                <p>Date: {{ prescription_date }}</p>
            </div>
            
            <div class="footer">
                <p>Generated by DrTranscribe AI System | {{ generation_timestamp }}</p>
                <p><em>This prescription was generated from AI-processed consultation data. Please verify all information before dispensing medications.</em></p>
            </div>
        </body>
        </html>
        """)
    
    async def generate_prescription(
        self,
        patient_id: str,
        doctor_id: str,
        medical_data: Dict[str, Any],
        patient_context: Dict[str, Any],
        doctor_info: Optional[Dict[str, Any]] = None,
        patient_info: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Generate a complete prescription from medical consultation data.
        
        Args:
            patient_id: Patient identifier
            doctor_id: Doctor identifier
            medical_data: Processed medical information
            patient_context: Patient history context
            doctor_info: Doctor information (optional)
            patient_info: Patient information (optional)
            
        Returns:
            Generated prescription data and file paths
        """
        try:
            self.logger.info(f"Generating prescription for patient {patient_id}")
            
            # Extract medication information
            medications = await self._process_medications(medical_data.get('medications', []))
            
            if not medications:
                self.logger.warning(f"No medications found for prescription generation - patient {patient_id}")
                return {
                    'status': 'no_medications',
                    'message': 'No medications were identified in the consultation'
                }
            
            # Validate medications against patient history
            validation_result = await self._validate_medications(medications, patient_context)
            
            if not validation_result['valid']:
                self.logger.warning(f"Medication validation failed: {validation_result['errors']}")
                return {
                    'status': 'validation_failed',
                    'errors': validation_result['errors'],
                    'warnings': validation_result.get('warnings', [])
                }
            
            # Prepare prescription data
            prescription_data = await self._prepare_prescription_data(
                patient_id, doctor_id, medical_data, patient_context,
                medications, doctor_info, patient_info
            )
            
            # Generate prescription forms
            forms = await self._generate_prescription_forms(prescription_data)
            
            # Create prescription record
            prescription_record = {
                'prescription_id': prescription_data['prescription_id'],
                'patient_id': patient_id,
                'doctor_id': doctor_id,
                'generated_at': datetime.now().isoformat(),
                'medications': medications,
                'diagnosis': medical_data.get('diagnosis', []),
                'symptoms': medical_data.get('symptoms', []),
                'follow_up_date': prescription_data.get('follow_up_date'),
                'forms': forms,
                'validation_warnings': validation_result.get('warnings', []),
                'status': 'generated'
            }
            
            self.logger.info(f"Prescription generated successfully: {prescription_data['prescription_id']}")
            
            return prescription_record
            
        except Exception as e:
            self.logger.error(f"Prescription generation failed for patient {patient_id}: {str(e)}")
            raise
    
    async def _process_medications(self, raw_medications: List[Any]) -> List[Dict[str, Any]]:
        """Process and structure medication information."""
        medications = []
        
        for med in raw_medications:
            if isinstance(med, dict):
                medication_text = med.get('text', '')
            else:
                medication_text = str(med)
            
            # Parse medication information (simplified - in production use medical NLP)
            parsed_med = await self._parse_medication_text(medication_text)
            if parsed_med:
                medications.append(parsed_med)
        
        return medications
    
    async def _parse_medication_text(self, medication_text: str) -> Optional[Dict[str, Any]]:
        """Parse medication text to extract structured information."""
        import re
        
        # This is a simplified parser - in production, use specialized medical NLP
        patterns = {
            'name': r'([A-Za-z]+(?:\s+[A-Za-z]+)?)',
            'dosage': r'(\d+(?:\.\d+)?\s*(?:mg|ml|g|units?))',
            'frequency': r'(once|twice|thrice|\d+\s*times?)\s*(?:daily|per day|a day)',
            'duration': r'for\s+(\d+\s*(?:days?|weeks?|months?))',
            'instructions': r'(before meals|after meals|with food|on empty stomach|as needed)'
        }
        
        medication = {}
        text_lower = medication_text.lower()
        
        # Extract name (first word typically)
        words = medication_text.split()
        if words:
            medication['name'] = words[0].title()
        
        # Extract dosage
        dosage_match = re.search(patterns['dosage'], text_lower)
        if dosage_match:
            medication['dosage'] = dosage_match.group(1)
        else:
            medication['dosage'] = "As directed"
        
        # Extract frequency
        freq_match = re.search(patterns['frequency'], text_lower)
        if freq_match:
            medication['frequency'] = freq_match.group(0)
        else:
            medication['frequency'] = "As directed"
        
        # Extract duration
        duration_match = re.search(patterns['duration'], text_lower)
        if duration_match:
            medication['duration'] = duration_match.group(1)
        else:
            medication['duration'] = "As prescribed"
        
        # Extract instructions
        instr_match = re.search(patterns['instructions'], text_lower)
        if instr_match:
            medication['instructions'] = instr_match.group(1).title()
        else:
            medication['instructions'] = "Follow doctor's instructions"
        
        # Add original text for reference
        medication['original_text'] = medication_text
        medication['confidence'] = 0.8  # Placeholder confidence
        
        return medication if medication.get('name') else None
    
    async def _validate_medications(
        self, 
        medications: List[Dict[str, Any]], 
        patient_context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Validate medications against patient history and known interactions."""
        validation_result = {
            'valid': True,
            'errors': [],
            'warnings': []
        }
        
        # Check for known allergies
        known_allergies = patient_context.get('known_allergies', [])
        if known_allergies:
            for medication in medications:
                med_name = medication.get('name', '').lower()
                for allergy in known_allergies:
                    if med_name in allergy.lower():
                        validation_result['errors'].append(
                            f"Potential allergy: {medication.get('name')} - {allergy}"
                        )
                        validation_result['valid'] = False
        
        # Check for duplicate medications
        med_names = [med.get('name', '').lower() for med in medications]
        duplicates = [name for name in med_names if med_names.count(name) > 1]
        if duplicates:
            validation_result['warnings'].append(
                f"Duplicate medications detected: {', '.join(set(duplicates))}"
            )
        
        # Check against recent medication history
        medication_history = patient_context.get('medication_history', [])
        if medication_history:
            recent_meds = []
            for hist in medication_history[-3:]:  # Last 3 consultations
                if hist.get('medications'):
                    recent_meds.extend(hist['medications'].lower().split(';'))
            
            for medication in medications:
                med_name = medication.get('name', '').lower()
                if any(med_name in recent_med for recent_med in recent_meds):
                    validation_result['warnings'].append(
                        f"Medication {medication.get('name')} was recently prescribed"
                    )
        
        return validation_result
    
    async def _prepare_prescription_data(
        self,
        patient_id: str,
        doctor_id: str,
        medical_data: Dict[str, Any],
        patient_context: Dict[str, Any],
        medications: List[Dict[str, Any]],
        doctor_info: Optional[Dict[str, Any]],
        patient_info: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Prepare all data needed for prescription generation."""
        
        prescription_id = f"RX_{patient_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        # Default doctor information
        default_doctor = {
            'name': f"Doctor {doctor_id}",
            'license': f"LIC_{doctor_id}",
            'specialty': "General Practice"
        }
        doctor_data = doctor_info or default_doctor
        
        # Default patient information
        default_patient = {
            'name': f"Patient {patient_id}",
            'age': "Unknown"
        }
        patient_data = patient_info or default_patient
        
        # Default clinic information
        clinic_info = {
            'name': "Medical Clinic",
            'address': "123 Medical Center, Healthcare City",
            'phone': "+1 (555) 123-4567"
        }
        
        # Process symptoms and diagnosis
        symptoms = "; ".join(medical_data.get('symptoms', ['Not specified']))
        diagnosis = "; ".join(medical_data.get('diagnosis', ['To be determined']))
        
        # Process follow-up instructions
        follow_up = medical_data.get('follow_up_instructions', {})
        follow_up_text = "; ".join(follow_up.get('instructions', ['Follow up as needed']))
        
        # Calculate follow-up date (default: 2 weeks from now)
        follow_up_date = (datetime.now() + timedelta(days=14)).strftime('%Y-%m-%d')
        
        prescription_data = {
            'prescription_id': prescription_id,
            'prescription_date': datetime.now().strftime('%Y-%m-%d'),
            'generation_timestamp': datetime.now().isoformat(),
            
            # Doctor information
            'doctor_name': doctor_data['name'],
            'doctor_license': doctor_data['license'],
            'doctor_specialty': doctor_data['specialty'],
            
            # Patient information
            'patient_id': patient_id,
            'patient_name': patient_data['name'],
            'patient_age': patient_data['age'],
            
            # Clinic information
            'clinic_name': clinic_info['name'],
            'clinic_address': clinic_info['address'],
            'clinic_phone': clinic_info['phone'],
            
            # Medical information
            'symptoms': symptoms,
            'diagnosis': diagnosis,
            'medications': medications,
            'additional_instructions': medical_data.get('clinical_summary', ''),
            'follow_up_instructions': follow_up_text,
            'follow_up_date': follow_up_date
        }
        
        return prescription_data
    
    async def _generate_prescription_forms(self, prescription_data: Dict[str, Any]) -> Dict[str, str]:
        """Generate prescription forms in multiple formats."""
        forms = {}
        
        # Generate HTML version
        html_content = self.prescription_template.render(**prescription_data)
        html_path = await self._save_html_prescription(prescription_data['prescription_id'], html_content)
        forms['html'] = html_path
        
        # Generate PDF version
        pdf_path = await self._generate_pdf_prescription(prescription_data)
        forms['pdf'] = pdf_path
        
        # Generate JSON version for API use
        json_path = await self._save_json_prescription(prescription_data)
        forms['json'] = json_path
        
        return forms
    
    async def _save_html_prescription(self, prescription_id: str, html_content: str) -> str:
        """Save HTML prescription to file."""
        output_dir = Path("./data/prescriptions/html")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        html_path = output_dir / f"{prescription_id}.html"
        
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return str(html_path)
    
    async def _generate_pdf_prescription(self, prescription_data: Dict[str, Any]) -> str:
        """Generate PDF prescription using ReportLab."""
        output_dir = Path("./data/prescriptions/pdf")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        pdf_path = output_dir / f"{prescription_data['prescription_id']}.pdf"
        
        # Create PDF document
        doc = SimpleDocTemplate(str(pdf_path), pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        # Header
        header_style = ParagraphStyle(
            'CustomHeader',
            parent=styles['Heading1'],
            alignment=1,  # Center alignment
            spaceAfter=20
        )
        
        story.append(Paragraph("PRESCRIPTION", header_style))
        story.append(Paragraph(prescription_data['clinic_name'], styles['Heading2']))
        story.append(Paragraph(f"{prescription_data['clinic_address']} | Phone: {prescription_data['clinic_phone']}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Doctor and Patient Info Table
        info_data = [
            ["Doctor Information", "Patient Information"],
            [f"Dr. {prescription_data['doctor_name']}", prescription_data['patient_name']],
            [f"License: {prescription_data['doctor_license']}", f"Patient ID: {prescription_data['patient_id']}"],
            [f"Specialty: {prescription_data['doctor_specialty']}", f"Age: {prescription_data['patient_age']}"],
            ["", f"Date: {prescription_data['prescription_date']}"]
        ]
        
        info_table = Table(info_data, colWidths=[3*inch, 3*inch])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), '#f0f0f0'),
            ('TEXTCOLOR', (0, 0), (-1, 0), black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), '#ffffff'),
            ('GRID', (0, 0), (-1, -1), 1, black)
        ]))
        
        story.append(info_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Medical Information
        story.append(Paragraph("Chief Complaints:", styles['Heading3']))
        story.append(Paragraph(prescription_data['symptoms'], styles['Normal']))
        story.append(Spacer(1, 0.1*inch))
        
        story.append(Paragraph("Diagnosis:", styles['Heading3']))
        story.append(Paragraph(prescription_data['diagnosis'], styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Medications
        story.append(Paragraph("Medications Prescribed:", styles['Heading3']))
        
        for i, med in enumerate(prescription_data['medications'], 1):
            med_text = f"""
            <b>{i}. {med.get('name', 'Unknown')}</b><br/>
            Dosage: {med.get('dosage', 'As directed')}<br/>
            Frequency: {med.get('frequency', 'As directed')}<br/>
            Duration: {med.get('duration', 'As prescribed')}<br/>
            Instructions: {med.get('instructions', 'Follow doctor\'s instructions')}
            """
            story.append(Paragraph(med_text, styles['Normal']))
            story.append(Spacer(1, 0.15*inch))
        
        # Additional Instructions
        if prescription_data.get('additional_instructions'):
            story.append(Paragraph("Additional Instructions:", styles['Heading3']))
            story.append(Paragraph(prescription_data['additional_instructions'], styles['Normal']))
            story.append(Spacer(1, 0.1*inch))
        
        # Follow-up
        story.append(Paragraph("Follow-up:", styles['Heading3']))
        story.append(Paragraph(prescription_data['follow_up_instructions'], styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
        
        # Signature
        signature_data = [
            ["", "____________________________"],
            ["", f"Dr. {prescription_data['doctor_name']}"],
            ["", "Digital Signature"],
            ["", f"Date: {prescription_data['prescription_date']}"]
        ]
        
        signature_table = Table(signature_data, colWidths=[4*inch, 2*inch])
        signature_table.setStyle(TableStyle([
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
            ('FONTNAME', (1, 1), (1, 1), 'Helvetica-Bold')
        ]))
        
        story.append(signature_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_text = f"""
        <font size="10" color="#666666">
        Generated by DrTranscribe AI System | {prescription_data['generation_timestamp']}<br/>
        <i>This prescription was generated from AI-processed consultation data. 
        Please verify all information before dispensing medications.</i>
        </font>
        """
        story.append(Paragraph(footer_text, styles['Normal']))
        
        # Build PDF
        await asyncio.to_thread(doc.build, story)
        
        return str(pdf_path)
    
    async def _save_json_prescription(self, prescription_data: Dict[str, Any]) -> str:
        """Save prescription data as JSON."""
        output_dir = Path("./data/prescriptions/json")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        json_path = output_dir / f"{prescription_data['prescription_id']}.json"
        
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(prescription_data, f, indent=2, ensure_ascii=False)
        
        return str(json_path)
    
    async def health_check(self) -> str:
        """Check prescription generation system health."""
        try:
            # Test template rendering
            test_data = {
                'prescription_id': 'TEST_001',
                'doctor_name': 'Test Doctor',
                'patient_name': 'Test Patient',
                'clinic_name': 'Test Clinic',
                'prescription_date': datetime.now().strftime('%Y-%m-%d'),
                'medications': [],
                'symptoms': 'Test symptoms',
                'diagnosis': 'Test diagnosis'
            }
            
            self.prescription_template.render(**test_data)
            return "healthy"
        except Exception:
            return "unhealthy"