/**
 * Export Module - PDF, Email, Clipboard, TXT export for drTranscribe
 *
 * Exposes DrTExport global with 4 methods:
 * - exportPDF(patient, doctorInfo)
 * - exportEmail(patient)
 * - exportClipboard(patient)
 * - exportTXT(patient)
 *
 * Reads edited text from textareas (drt-edit-*) in the post-session panel.
 */
(function () {
    'use strict';

    const FIELD_KEYS = ['chief_complaint', 'diagnosis', 'medicine', 'advice', 'next_steps'];
    const FIELD_LABELS = {
        chief_complaint: 'Chief Complaint',
        diagnosis: 'Diagnosis',
        medicine: 'Medicine',
        advice: 'Advice',
        next_steps: 'Next Steps'
    };

    function getEditedData() {
        const data = {};
        for (const key of FIELD_KEYS) {
            const el = document.getElementById('drt-edit-' + key);
            data[key] = el ? el.value.trim() : '';
        }
        return data;
    }

    function getDateString() {
        return new Date().toLocaleDateString('en-IN', {
            day: '2-digit', month: 'short', year: 'numeric'
        });
    }

    function getTimestamp() {
        return new Date().toLocaleString('en-IN', {
            day: '2-digit', month: 'short', year: 'numeric',
            hour: '2-digit', minute: '2-digit'
        });
    }

    function safeName(name) {
        return (name || 'patient').replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
    }

    function formatPlainText(patient, data, date) {
        const lines = [];
        const sep = '\u2550'.repeat(39);
        const thin = '\u2500'.repeat(39);

        lines.push(sep);
        lines.push('        CONSULTATION NOTES');
        lines.push(sep);
        lines.push('Date: ' + date);
        lines.push('');
        lines.push('PATIENT DETAILS');
        lines.push(thin);
        lines.push('Name: ' + (patient.name || '-') + ' | Age: ' + (patient.age || '-') + ' | Gender: ' + (patient.gender || '-'));
        lines.push('');

        for (const key of FIELD_KEYS) {
            const val = data[key];
            if (val) {
                lines.push(FIELD_LABELS[key].toUpperCase());
                lines.push(thin);
                lines.push(val);
                lines.push('');
            }
        }

        lines.push(sep);
        lines.push('Generated by drTranscribe');
        return lines.join('\n');
    }

    // ─── PDF Export ─────────────────────────────────────────────

    function exportPDF(patient, doctorInfo) {
        const jsPDF = window.jspdf && window.jspdf.jsPDF;
        if (!jsPDF) {
            alert('PDF library not loaded. Please try again.');
            return;
        }

        const doc = new jsPDF('p', 'mm', 'a4');
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        const contentWidth = pageWidth - margin * 2;
        let y = margin;
        const data = getEditedData();
        const date = getDateString();

        // Helper: check page break
        function checkPageBreak(neededHeight) {
            if (y + neededHeight > pageHeight - 25) {
                doc.addPage();
                y = margin;
            }
        }

        // Helper: write wrapped text and return new Y
        function writeWrapped(text, x, startY, maxWidth, lineHeight) {
            const lines = doc.splitTextToSize(text, maxWidth);
            for (const line of lines) {
                checkPageBreak(lineHeight);
                doc.text(line, x, startY);
                startY += lineHeight;
            }
            return startY;
        }

        // ─── Header ─────────────────────────────────────────
        const doctorName = (doctorInfo && doctorInfo.doctorName) || '';
        const clinicName = (doctorInfo && doctorInfo.clinicName) || '';

        if (doctorName) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(18);
            doc.text(doctorName, margin, y);
            y += 7;
        }

        if (clinicName) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
            doc.setTextColor(100, 100, 100);
            doc.text(clinicName, margin, y);
            y += 5;
        }

        // Date (right-aligned)
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('Date: ' + date, pageWidth - margin, (doctorName ? margin : y), { align: 'right' });
        doc.setTextColor(0, 0, 0);

        if (doctorName || clinicName) y += 3;

        // Horizontal rule
        doc.setDrawColor(180, 180, 180);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y);
        y += 8;

        // ─── Patient Details ────────────────────────────────
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.text('Patient: ' + (patient.name || '-'), margin, y);
        doc.text('Age: ' + (patient.age || '-') + '    Gender: ' + (patient.gender || '-'), margin + 90, y);
        y += 10;

        // ─── Rx Symbol ──────────────────────────────────────
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(20);
        doc.text('Rx', margin, y);
        y += 10;

        // ─── Sections ───────────────────────────────────────
        doc.setFontSize(11);

        for (const key of FIELD_KEYS) {
            const val = data[key];
            if (!val) continue;

            checkPageBreak(15);

            // Section title
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(11);
            doc.text(FIELD_LABELS[key].toUpperCase(), margin, y);
            y += 6;

            // Section content
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            y = writeWrapped(val, margin, y, contentWidth, 5);
            y += 6;
        }

        // ─── Footer ─────────────────────────────────────────
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by drTranscribe | ' + getTimestamp(), margin, pageHeight - 10);

        // Download
        const filename = 'prescription_' + safeName(patient.name) + '_' + date.replace(/\s/g, '-') + '.pdf';
        doc.save(filename);
    }

    // ─── Email Export ───────────────────────────────────────────

    function exportEmail(patient) {
        const data = getEditedData();
        const date = getDateString();
        const subject = encodeURIComponent('Consultation Notes - ' + (patient.name || 'Patient') + ' - ' + date);
        const body = encodeURIComponent(formatPlainText(patient, data, date));
        const gmailUrl = 'https://mail.google.com/mail/?view=cm&su=' + subject + '&body=' + body;

        window.open(gmailUrl, '_blank');

        // Also copy to clipboard as fallback
        exportClipboard(patient);
        return true;
    }

    // ─── Clipboard Export ───────────────────────────────────────

    function exportClipboard(patient) {
        const data = getEditedData();
        const date = getDateString();
        const text = formatPlainText(patient, data, date);

        try {
            navigator.clipboard.writeText(text);
            return true;
        } catch {
            // Fallback
            const ta = document.createElement('textarea');
            ta.value = text;
            ta.style.position = 'fixed';
            ta.style.left = '-9999px';
            document.body.appendChild(ta);
            ta.select();
            try {
                document.execCommand('copy');
                return true;
            } catch {
                return false;
            } finally {
                document.body.removeChild(ta);
            }
        }
    }

    // ─── TXT Export ─────────────────────────────────────────────

    function exportTXT(patient) {
        const data = getEditedData();
        const date = getDateString();
        const text = formatPlainText(patient, data, date);

        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'consultation_' + safeName(patient.name) + '_' + date.replace(/\s/g, '-') + '.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    // ─── Expose Global ──────────────────────────────────────────

    window.DrTExport = {
        exportPDF: exportPDF,
        exportEmail: exportEmail,
        exportClipboard: exportClipboard,
        exportTXT: exportTXT
    };
})();
